### ISSUE TITLE
Update modeling tutorial

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#10]
Related to #5, we need to update the modeling tutorial to include all changes since the last release. 

We should also seriously get round to getting our hands dirty on videos (#3), though this is something we could add after the release.

**Comment by kavonszadkowski** [comment]
Are you planning to work on this today, @SamuelYaron? I'd like to make a few changes to various parts of the documentation and I'd like to avoid merge conflicts.

**Comment by SamuelYaron** [comment]
In order of my discomforts I will work on it later this day. So there will be no merge conflicts when you edit the documentation in the next hours

**Comment by kavonszadkowski** [comment]
Overhauling the wiki is done. I updated everything and added a few missing hints I could think of. It would be great if you could still add the description of how to add the sensors.
