### ISSUE TITLE
install error on blender 2.76b in Ubuntu14.04/Windows7-64b

### ISSUE THREAD

**Issue by pgaudillere** [rock-simulation/phobos#105]
Hi,
I tried to install phobos on Blender 2.76b (linux Ubuntu14.04) and Blender 2.75a (Windows 7-64b), and I got the folowing error
![blender-phobos](https://cloud.githubusercontent.com/assets/3862958/12220013/da7855e0-b77d-11e5-8ad1-81dbba1b53c4.png)

any idea? Do I have to try on Blender 2.71?

best regards,

Pierre

**Comment by pgaudillere** [comment]
![blender-phobos](https://cloud.githubusercontent.com/assets/3862958/12219996/5ea8580c-b77d-11e5-8143-15ab4164d316.png)

**Comment by kavonszadkowski** [comment]
The problem seems to arise when Phobos tries to import its predefined components, such as sensors. I myself am running on Ubuntu 14.04 and Blender 2.76b, so that shouldn't be the issue, but I see from the error message that error occurred on Windows?

**Comment by pgaudillere** [comment]
Yes I tried to import the 0.7 zip release from github on both windows and linux, with no success. But the install script on linux from the git snapshot works. I wonder if there are missing files in the zip file..
Now I have difficulties to export my robot to urdf (a bit too complicated for a first try I think), but it is another subject.. Thanks for your help, and this great addon, I was thinking about doing one myself, but yours looks great!

**Comment by oschumac** [comment]
Hi i had the same prob. I have copied the setting folder to the script folder now everything runs fine. CU
