### ISSUE TITLE
Exporting SMURF on branch develop

### ISSUE THREAD

**Issue by Rauldg** [rock-simulation/phobos#129]
Hello,

I am using the branch develop on blender 2.79

The export model functionality of URDF and Meshes seem to be fine but SMURF exportation is not happening. The error occurs because here

https://github.com/rock-simulation/phobos/blob/f25e022cae6df07d4b848ca57d78cbb72276eb4b/phobos/io/entities/entities.py#L60

The function ```exportGenericEntity``` is register as the function to call when requesting a smurf export. The function ```exportGenericEntity``` is expecting no arguments, but is also doing nothing. 

Should it do something?

I guess that this is either a bug or a missing feature.

@dfki-bruce is also interesting in this issue

**Comment by Rauldg** [comment]
This is the traceback of the error:

```

Traceback (most recent call last):
  File "/home/dfki.uni-bremen.de/rdominguez/.config/blender/2.79/scripts/addons/phobos/operators/io.py", line 148, in invoke
    return self.execute(context)
  File "/home/dfki.uni-bremen.de/rdominguez/.config/blender/2.79/scripts/addons/phobos/operators/io.py", line 174, in execute
    exportModel(root, exportpath)
  File "/home/dfki.uni-bremen.de/rdominguez/.config/blender/2.79/scripts/addons/phobos/operators/io.py", line 217, in exportModel
    entities.entity_types[entitytype]['export'](model, model_path)
TypeError: exportGenericEntity() takes 0 positional arguments but 2 were given

location: <unknown location>:-1

location: <unknown location>:-1

```

**Comment by kavonszadkowski** [comment]
Thx for the report. Interestingly, this error never occurred with Blender 2.78, could be due to differing Python versions, but there is something amiss with the export function registration. I'm a bit swamped right now, will try to sort this out today or tomorrow.

**Comment by kavonszadkowski** [comment]
This has been fixed in the meanwhile, thanks again for pointing it out!
