### ISSUE TITLE
Motor export

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#13]
It seems that (at least in some cases) motors get exported to *_motors.yml* for joints irrespective of there being an actual motor definition for the joint.

**Comment by JanPaul73** [comment]
I have this issue even if the joints are fixed and passive.

**Comment by kavonszadkowski** [comment]
Turned out to be a bug introduced by a generalisation of the type-specific property filtering during the robot dictionary creation. Fixed it with 5dcf7b6e3411bae96bce7e8ea18608f3b4b26bfe.
