### ISSUE TITLE
Share meshes does not work.

### ISSUE THREAD

**Issue by JanPaul73** [rock-simulation/phobos#14]
I had a situation where mesh "doorKnobStart.000" was shared for objects named like "doorKnobEnd.000" and only "doorKnobStart.008.bobj" was exported.
Also this is not easy to undo.
It should be choosable what the shared mesh name will be.

**Comment by SamuelYaron** [comment]
The individual naming of shared meshes in now possible(it will be merged into master branch after final testing til end of week). You can undo your mesh sharing instantly with blenders builtin undo mechanism. I didn't find a way to undo the sharing in blender later on yet, but if you just want to export the meshes separately you can delete the objects geometry/sharedMeshFile custom properties and that will do it for exporting out of blender.

**Comment by kavonszadkowski** [comment]
Smells like documentation to me. ;)

**Comment by SamuelYaron** [comment]
See Issue #9 for the documentation. After testing I merged into master and closed this Issue

**Comment by SamuelYaron** [comment]
This morning I found a way to undo the mesh sharing by accident. I implemented and pushed the operator already and will modify the docs asap.
