### ISSUE TITLE
Exporting light sources from blender

### ISSUE THREAD

**Issue by JanPaul73** [rock-simulation/phobos#19]
Exporting light sources from blender would be a nice addition.

**Comment by kavonszadkowski** [comment]
Very true and already planned for a later release, probably 0.7.

**Comment by kavonszadkowski** [comment]
What's the status on this issue?

**Comment by srahms** [comment]
Right, I should have written a comment on that. Light source export works for lights attached to a robot. Should this be closed, or left open until all light sources can be exported?

**Comment by kavonszadkowski** [comment]
Seems like exporting light sources to scenes should be straightforward. Let's discuss this next time we meet and close this issue then.

**Comment by kavonszadkowski** [comment]
I made some changes to the implementation. Should work fine and now works for solitary light objects export to SMURF scenes. Probably should be double checked by @srahms.
