### ISSUE TITLE
Sensor creation

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#24]
Adding sensors is not yet as nice as we would like it. For instance, Joint6DOF sensors need to be added to fixed joints connected to the joints where forces and torques should be measured and sensors attached to that fixed link, cameras are simply anchored to a link while NodeVelocity/NodePosition Sensors can have long lists of nodes they are measuring and don't need to be attached to any link in particular. We need think of a way to make that distinction clearer in the GUI and also document everything properly (though this also relates to MARS documentation itself).

**Comment by SamuelYaron** [comment]
There exists some initial documentation in the wiki now (Basic Modelling).

**Comment by SamuelYaron** [comment]
I also added support for the Joint6DOF to phobos in a separate branch. it will be merged after testing.
