### ISSUE TITLE
"Name Robot" should work on multiple selected robots.

### ISSUE THREAD

**Issue by JanPaul73** [rock-simulation/phobos#25]
"Name Robot" should work on multiple selected robots. Then it would be possible to for example export a large number of similar objects that are expected to move independently (e.g. spheres roughly representing water particles).

**Comment by kavonszadkowski** [comment]
This is something that relates to us having to complete the scene export. We obviously have to differentiate between the name of the robot *model* and the robot *entity*, the former referring to a robot *class* if you will and the latter to an *instance* of that class.

I think we won't touch this until we've decided how that is going to work, including namespaces for robots. Meanwhile, you can always simply use the batch functionality of the *Edit custom property* operator and simply set "modelname" yourself.

**Comment by kavonszadkowski** [comment]
I'm assuming this can be closed, not that #35 is closed?

**Comment by SamuelYaron** [comment]
Well the Name Robot Operator does not work on multiple objects. But now we have the namespacing and robot 'puppet' system to create a scene with a number of independent similar robots. So I think this is not needed anymore.
