### ISSUE TITLE
consistent (SI) units for joints/motors

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#27]
Joint and Motor maximum speeds currently have no consistent units. We should provide two units for angular speed in Phobos (rad/s and Hz) and one for linear (m/s). As for the output written in URDF, we should use the standard unit defined there for angular speed and use the same in SMURF for the motors. We should double-check which unit is expected by MARS (Should be the one currently written to SMURF).

**Comment by SamuelYaron** [comment]
We decided to use rad/s, m/s, Nm, N and °/s as input; rad/s, m/s, N and Nm are exported

**Comment by SamuelYaron** [comment]
Feature is merged into master
