### ISSUE TITLE
consistency between joint and motor constraints

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#29]
By default, joint constraints and motor constraints should be the same, i.e. when a motor gets attached to a joint with defined constraints, the invoke function of the operator should set the parameters accordingly.

The check robot model function should test for inconsistencies between joint and motor constraints.

**Comment by SamuelYaron** [comment]
Invoke functions are created. The testing will be added in milestone 0.7 or 0.8. The Issue will be moved to Milestone 0.7
