### ISSUE TITLE
Cant import URDF in Release v2.0.0

### ISSUE THREAD

**Issue by a-kest** [rock-simulation/phobos#296]
Hello,
for a project I wanted to edit a URDF file using Phobos.
However, similar to #291 I get an error while importing the urdf file:

Screen goes here

1. Clone the Phobos repository (Phobos v2.0.0)
2. Zip the Phobos folder in the Phobos repository
3. Download Blender v3.3LTS
4. Add the Phobos zip file as an add-on to blender.
5. Open the sidebar, select Phobos, scroll down and click Import Robot Model
6. Try importing any URDF file (tested with 5 urdf files including the one stated in #291)
7. Error should appear

Using:
 - OS: Ubuntu 22.04LTS
 - Phobos v2.0.0
 - Blender v3.3LTS

**Comment by hwiedPro** [comment]
Thanks for your contribution and using phobos. I consider this issue as solved, please reopen and specify further in case this issue persists for you. :)
