### ISSUE TITLE
Add a simple Tutorial to find the Phobos Tollbox Page.

### ISSUE THREAD

**Issue by MaartenBehn** [rock-simulation/phobos#299]
**Is your feature request related to a problem? Please describe.**
It took me about two hours to find the Phobos Toolbox page. 
This is how my Blender Window looked and could not find the toolbox window. 
![Screenshot from 2023-07-13 17-00-59](https://github.com/dfki-ric/phobos/assets/46872913/ec17dc30-3ffe-4f56-b8d5-983a62a878aa)

Finally, I asked my coworker and he showed me this tiny arrow you have to click to open the window.
The entire time I thought the plugin crashed mid-start up and that's why the window is not showing up.

Now I found the window and Blender Window looks like this.
![Screenshot from 2023-07-13 17-01-32](https://github.com/dfki-ric/phobos/assets/46872913/5d7fbff1-55db-47cb-84cd-881af0d10ad4)

**Describe the solution you'd like**
Could you guys add a Tutorial to the First Steps Page of the Wiki on how to find the Tollbox window?
So new users will have an easier time in the future. :)

**Comment by prawinsankar-ta** [comment]
Hello!|

I'm also working on this package for my project. The installation module gets installed and later I'm not able to find the toolbox?

**Comment by MaartenBehn** [comment]
Its likely that you Plug-in works fine and you just need to click that tiny arrow Button. :) 

![Screenshot_20230717-122551_Shady_Launcher~2.png](https://github.com/dfki-ric/phobos/assets/46872913/c3fd6872-a86e-4385-86d3-2eb4c31620c5)

**Comment by hwiedPro** [comment]
Hi,
thanks for the contribution. It's explained in the README. Normally including an image, but somehow the link there is currently broken. We'll fix this asap.

**Comment by hwiedPro** [comment]
The image link in the README is fixed. Therefore I close this
