### ISSUE TITLE
URDF joint data export allows invalid joints

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#32]
It's possible to export an invalid joint, namely Phobos is happy to export a joint with out maximum effort, thus creating an invalid URDF. We should check again for all joint parameters and notify the user if there is information missing and therefore the URDF created is not valid.

We should not prevent export though, as it might be the case that some people want to edit effort and other parameters manually or via some scripts later on.

**Comment by srahms** [comment]
Fixed. Missing values that render the produced URDF invalid, but do not prevent a successful export, produce warnings now.
