### ISSUE TITLE
Instances of same robot get same position in smurfs.

### ISSUE THREAD

**Issue by JanPaul73** [rock-simulation/phobos#35]
When having multiple copies of a robot in a scene sharing the same robot name, they all get exported but are set to the same position in the ".smurfs"-scene-file although they have different positions in Blender.

**Comment by kavonszadkowski** [comment]
This is related to #25 as it also results from the non-distinction between robot names and entity names. Should be closed in Phobos 0.7 the latest, but I have the feeling that this is something we should fix pretty soon as some people would need this functionality.
