### ISSUE TITLE
Export of meshes using modifiers.

### ISSUE THREAD

**Issue by JanPaul73** [rock-simulation/phobos#38]
Exporting meshes with modifiers tends to crash Blender and MARS when using .obj and only MARS when using .bobj. Applying the modifiers before solves the problem, so when exporting (which to my knowledge includes making a copy of the object), applying all the modifiers to the copy should solve the problem.

Another problem is probably active here: The copy is moved to [0,0,0], right? If it uses a boolean operation with another object "A" or is for example deformed by a lattice "A", then the object will get corrupted by moving it away from its current position (as the other object "A" will stay in place). So the object should be
1. copied in place
2. get all modifierts applied
3. be set to [0,0,0] or wherever necessary
4. then get exported

**Comment by kavonszadkowski** [comment]
Not a pressing issue right now. Feel free to create a pull request, though.

**Comment by JanPaul73** [comment]
This is fixed for BOBJ now (see my pull request), but still open for OBJ.

**Comment by SamuelYaron** [comment]
Done for obj and stl in pull request #98 .
