### ISSUE TITLE
Capsules

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#41]
URDF does not really support capsules. To still be able to create them and use them in MARS, we can emulate a capsule using a cylinder and two spheres in URDF and annotate that it really should be a capsule in SMURF.  
Currently, capsules are treated as meshes in Phobos.

This should be implemented properly at the same time as it is implemented in the MARS import.

**Comment by srahms** [comment]
Capsules are now treated as a cylinder plus two spheres each during URDF export. The information needed to properly import the capsules into MARS is stored in *_collisions.yml. The MARS import itself is currently work in progress.
