### ISSUE TITLE
orientation of cameras

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#44]
Camera sensors are attached to a link to determine their position and orientation in the model. Importing a model in MARS, the camera points in X direction, with Z up. We must ensure in Phobos that a camera is always oriented accordingly to its parent link, so that the camera perspective shown in Phobos is the one used in MARS.

**Comment by SamuelYaron** [comment]
Fixed with 118fe507e1f0694bb5c350ca9c8cd4efe1938983.
