### ISSUE TITLE
Import defs fails with distributed YAML

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#56]
I've encountered this on Ubuntu 14.04 and on MacOS 10: When freshly installing Phobos, if the python-yaml package distributed with Phobos is chosen rather than the system-installed one, loading Phobos into Blender fails as Blender is unable to import *defs.py*.

This might be related to issue #55.

**Comment by SamuelYaron** [comment]
I think you're right and this problem is related to issue #55. After fixing the defs folder problem both, installing distributed and system, works fine for me.
