### ISSUE TITLE
Repository is getting a bit cluttered

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#58]
We should think of restructuring our files - the repository is getting a bit cluttered and one has to scroll a lot to get to the README due to all the loose files.

**Comment by SamuelYaron** [comment]
Maybe we should combine this issue with our plan to make phobos ready to use it without installing it or even using it without the GUI. They both need restructuring as well

**Comment by kavonszadkowski** [comment]
Repository looks a lot better now. There might be some details left still to cope with, but we're good for now.
