### ISSUE TITLE
Collision bitmasks

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#61]
I just fixed a bug in the parsing of collision bitmasks from the collision groups in Phobos (8396a69bcebd752) - the binary string had to be inverted and limited to 16 bits. Since Blender allows for 20 layers, the last 4 are now silently ignored and thus simply fail to be exported if the user uses them for collision configuration.

We could simply throw a warning upon model checking if there are other values than 0 in these group layers, or we could address the problem of MARS not being able to use more than 16 bits. Since the next logical step would be 32 bits, however, this would result in the problem of Blender not being able to support these internally. We could introduce a new collision group definition manually instead of using the rigid body world property, this however would in the long term make it impossible to use physics simulation in Blender directly.

Thus I propose to cap the collision bitmasks to 16 and throw an appropriate warning.

**Comment by BiYonic** [comment]
The issue will be resolved with the next stable release.
