### ISSUE TITLE
URDF export: meshes should be a flag and exported anyway if file type has changed

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#69]
Currently, meshes imported via the URDF import get a custom property *filename* which, if set, leads to the mesh not being exported to prevent overwriting of the original meshes.

This behavior should probably be an option in the importer that the user can set. Additionally, if the user chooses to export to a different file type, the meshes should be exported despite there being a *filename* entry.

**Comment by SamuelYaron** [comment]
This Issue will be solved in one step with Issue 72
