### ISSUE TITLE
URDF importer does not work correctly

### ISSUE THREAD

**Issue by goldhoorn** [rock-simulation/phobos#70]
I tried to import models from the following file:

https://github.com/goldhoorn/p2os/blob/master/p2os_urdf/defs/model.urdf

however the collision's seems valid but all visuals are misplaced.

(same is true for other urfd files from this package)

**Comment by kavonszadkowski** [comment]
I reckon we'll first have to check whether the URDFs you mentioned are valid to begin with.

**Comment by goldhoorn** [comment]
It's auto generated by some script (what does not mean that is is 
correct) but is 'common'
however you can find under the link i already posted.

On 30.07.2015 11:38, Kai von Szadkowski wrote:
>
> I reckon we'll first have to check whether the URDFs you mentioned are 
> valid to begin with.
>
> —
> Reply to this email directly or 
> https://github.com/rock-simulation/phobos/issues/70#issuecomment-126243340https://github.com/rock-simulation/phobos/issues/70#issuecomment-126243340.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik
