### ISSUE TITLE
PyDoc for marssceneparser

### ISSUE THREAD

**Issue by SamuelYaron** [rock-simulation/phobos#75]
I don't know anything about the marsscenes at all so I'm not the right one to write the pyDoc for this module. I think @srahms or @kavonszadkowski  is the right one for the job?

**Comment by srahms** [comment]
I'm not quite sure why this file is still there, since its functionality has been transferred to the importer long ago. I will delete it and write the comments for the MARSModelParser in the importer.

**Comment by srahms** [comment]
Done and done.
