### ISSUE TITLE
PyDoc for marssceneexport

### ISSUE THREAD

**Issue by SamuelYaron** [rock-simulation/phobos#76]
For the same reasons as for Issue #75 I can not write the PyDocs here.

**Comment by srahms** [comment]
If I remember correctly, a MARS scene export does not actually exist nor is it planned, so this is most likely incomplete code that won't be needed at any point. Can you confirm this, @kavonszadkowski ?
If so, this should be removed from the repository.

**Comment by srahms** [comment]
I was right. Deleted the file for now from the repository.
