### ISSUE TITLE
Model import with Blender 2.76

### ISSUE THREAD

**Issue by mmeder** [rock-simulation/phobos#89]
I just encountered a problem, that when using Phobos with Blender version 2.76 the import of models (urdf) does not work, or only partially with all the parenting gone. Downgrading Blender to 2.69 the import works again. Also the import worked with the previous version 2.75 I had installed.

**Comment by kavonszadkowski** [comment]
Thanks for the info, we haven't tested Phobos with Blender 2.76, yet, so we'll have to look into the problem.
