### ISSUE TITLE
Test and document functionality to reuse meshes

### ISSUE THREAD

**Issue by kavonszadkowski** [rock-simulation/phobos#9]
The functionality to share meshes between Blender objects needs final testing and documentation before the next release. We also need to double-check whether it works nicely together with the pre-existing functionality to avoid mesh re-export when importing and exporting URDF.

**Comment by SamuelYaron** [comment]
I tested it as good as I could. I also documented it in Basic Modelling - Optimization. Please review the doc and close the Issue if everything is okay.

**Comment by SamuelYaron** [comment]
As I mentioned in Issue #14 I have to alter the docs to fit the new way to undo mesh sharing.

**Comment by SamuelYaron** [comment]
Please review doc and then close the Issue if everything is okay.
